name: Package plugin
on:
  push:
    branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        run: python3 make_release.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: plugin
          path: |
            DeDRM_tools_*.zip
            DeDRM_tools.zip
     
      - name: Prepare release
        run: cp DeDRM_tools.zip DeDRM_alpha_${{ github.sha }}.zip


      - uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: noDRM/DeDRM_tools_autorelease 
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.AUTORELEASE_KEY }}

      - name: Auto-release
        id: autorelease
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: autorelease_${{ github.sha }}
          repository: noDRM/DeDRM_tools_autorelease
          token: ${{ secrets.AUTORELEASE_KEY }}
          name: Automatic alpha release with latest changes
          body: |
            This release is automatically generated by Github for each commit. 

            This means, every time a change is made to the repo, a release with an untested copy of the plugin at that stage will be created. This will contain the most up-to-date code, but it's not tested at all and may be broken.

            Last update based on Git commit [${{ github.sha }}](https://github.com/noDRM/DeDRM_tools/commit/${{ github.sha }}).
          prerelease: true
          draft: false
          files: DeDRM_alpha_${{ github.sha }}.zip
